
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - chaos.pumba.dev
  resources:
  - killcontainers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chaos.pumba.dev
  resources:
  - killcontainers/status
  verbs:
  - get
  - patch
  - update
